# Generated by Django 4.2 on 2023-04-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='id_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oreder2order', to='orders.order'),
        ),
    ]
