# Generated by Django 4.2 on 2023-06-04 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderproduct_id_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='PENDING', max_length=100),
        ),
    ]
