# Generated by Django 4.2 on 2023-06-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_date_joined_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_joined',
            field=models.DateTimeField(default='06/04/2023, 19:52:06'),
        ),
    ]
