# Generated by Django 4.2 on 2023-06-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_joined',
            field=models.CharField(default='06/04/2023, 19:55:07', max_length=1000),
        ),
    ]
