# Generated by Django 4.2 on 2023-06-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_joined',
            field=models.CharField(default='06/04/2023, 20:10:13', max_length=1000),
        ),
    ]
